server:
  port: 8089

spring:
  application:
    name: authentication-service

  datasource:
    url: jdbc:mysql://localhost:3306/hotel_auth
    username: root
    password: "@,ASD123!!ria"

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  cloud:
    config:
      uri: http://localhost:8085

  config:
    import: optional:configserver:http://localhost:8085

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: hotelSecretKey
  expiration: 3600000  # 1 hour in ms
