server:
  port: 8085

spring:
  application:
    name: config-service

  cloud:
    config:
      server:
        git:
          uri: https://github.com/Iamriatandan/hotel-management-config
          clone-on-start: true
          default-label: main

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
